theme: jekyll-theme-minimal
title: MASAMB 2027
description: Hello and welcome to the 33rd Workshop on Mathematical and Statistical Aspects of Molecular Biology!
show_downloads: false
navigation:
  - title: Home
    url: /
  - title: Registration
    url: registration
  - title: Absctract submission
    url: abstract
  - title: Programme
    url: programme
  - title: Venue
    url: venue
  - title: Accommodation
    url: accomodation
  - title: Scientific commitee
    url: sci_commitee
  - title: Organising commitee
    url: local_commitee
